# Generated by Django 5.2.13 on 2026-04-17 11:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecurrenceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('daily', 'Quotidienne'), ('weekly', 'Hebdomadaire'), ('monthly', 'Mensuelle')], max_length=20)),
                ('interval', models.PositiveIntegerField(default=1)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('count', models.PositiveIntegerField(blank=True, null=True)),
                ('days_of_week', models.CharField(blank=True, help_text='0=lundi ... 6=dimanche', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_group', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
            ],
            options={
                'ordering': ['start_datetime'],
            },
        ),
    ]
